//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace J2EE_SOAPtester.WordSoap {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.word.hu/Word")]
    public partial class errorStub : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string fieldField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.word.hu/Word", ConfigurationName="WordSoap.Word")]
    public interface Word {
        
        // CODEGEN: Parameter 'edited' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/editTranslation", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(J2EE_SOAPtester.WordSoap.errorStub), Action="http://www.word.hu/Word/editTranslation", Name="WordFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="edited")]
        J2EE_SOAPtester.WordSoap.EditTranslationResponse EditTranslation(J2EE_SOAPtester.WordSoap.EditTranslation request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/editTranslation", ReplyAction="*")]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.EditTranslationResponse> EditTranslationAsync(J2EE_SOAPtester.WordSoap.EditTranslation request);
        
        // CODEGEN: Parameter 'deleted' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/deleteTranslation", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(J2EE_SOAPtester.WordSoap.errorStub), Action="http://www.word.hu/Word/deleteTranslation", Name="WordFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="deleted")]
        J2EE_SOAPtester.WordSoap.DeleteTranslationResponse DeleteTranslation(J2EE_SOAPtester.WordSoap.DeleteTranslation request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/deleteTranslation", ReplyAction="*")]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.DeleteTranslationResponse> DeleteTranslationAsync(J2EE_SOAPtester.WordSoap.DeleteTranslation request);
        
        // CODEGEN: Parameter 'deleted' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/deleteDictionary", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(J2EE_SOAPtester.WordSoap.errorStub), Action="http://www.word.hu/Word/deleteDictionary", Name="WordFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="deleted")]
        J2EE_SOAPtester.WordSoap.DeleteDictionaryResponse DeleteDictionary(J2EE_SOAPtester.WordSoap.DeleteDictionary request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/deleteDictionary", ReplyAction="*")]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.DeleteDictionaryResponse> DeleteDictionaryAsync(J2EE_SOAPtester.WordSoap.DeleteDictionary request);
        
        // CODEGEN: Parameter 'Translation' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/getTranslationsForDictionary", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(J2EE_SOAPtester.WordSoap.errorStub), Action="http://www.word.hu/Word/getTranslationsForDictionary", Name="WordFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Translation")]
        J2EE_SOAPtester.WordSoap.GetTranslationsForDictionaryResponse GetTranslationsForDictionary(J2EE_SOAPtester.WordSoap.GetTranslationsForDictionary request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/getTranslationsForDictionary", ReplyAction="*")]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.GetTranslationsForDictionaryResponse> GetTranslationsForDictionaryAsync(J2EE_SOAPtester.WordSoap.GetTranslationsForDictionary request);
        
        // CODEGEN: Parameter 'Dictionary' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/getDictionaries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Dictionary")]
        J2EE_SOAPtester.WordSoap.GetDictionariesResponse GetDictionaries(J2EE_SOAPtester.WordSoap.GetDictionaries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/getDictionaries", ReplyAction="*")]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.GetDictionariesResponse> GetDictionariesAsync(J2EE_SOAPtester.WordSoap.GetDictionaries request);
        
        // CODEGEN: Parameter 'created' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/newTranslation", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(J2EE_SOAPtester.WordSoap.errorStub), Action="http://www.word.hu/Word/newTranslation", Name="WordFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="created")]
        J2EE_SOAPtester.WordSoap.NewTranslationResponse NewTranslation(J2EE_SOAPtester.WordSoap.NewTranslation request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/newTranslation", ReplyAction="*")]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.NewTranslationResponse> NewTranslationAsync(J2EE_SOAPtester.WordSoap.NewTranslation request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/errorTest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(J2EE_SOAPtester.WordSoap.errorStub), Action="http://www.word.hu/Word/errorTest", Name="WordFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ErrorTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/errorTest", ReplyAction="*")]
        System.Threading.Tasks.Task ErrorTestAsync();
        
        // CODEGEN: Parameter 'created' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/newDictionary", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(J2EE_SOAPtester.WordSoap.errorStub), Action="http://www.word.hu/Word/newDictionary", Name="WordFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="created")]
        J2EE_SOAPtester.WordSoap.NewDictionaryResponse NewDictionary(J2EE_SOAPtester.WordSoap.NewDictionary request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.word.hu/Word/newDictionary", ReplyAction="*")]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.NewDictionaryResponse> NewDictionaryAsync(J2EE_SOAPtester.WordSoap.NewDictionary request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditTranslation", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class EditTranslation {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string to;
        
        public EditTranslation() {
        }
        
        public EditTranslation(long id, string from, string to) {
            this.id = id;
            this.from = from;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditTranslationResponse", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class EditTranslationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool edited;
        
        public EditTranslationResponse() {
        }
        
        public EditTranslationResponse(bool edited) {
            this.edited = edited;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteTranslation", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class DeleteTranslation {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id;
        
        public DeleteTranslation() {
        }
        
        public DeleteTranslation(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteTranslationResponse", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class DeleteTranslationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool deleted;
        
        public DeleteTranslationResponse() {
        }
        
        public DeleteTranslationResponse(bool deleted) {
            this.deleted = deleted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDictionary", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class DeleteDictionary {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public DeleteDictionary() {
        }
        
        public DeleteDictionary(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDictionaryResponse", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class DeleteDictionaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool deleted;
        
        public DeleteDictionaryResponse() {
        }
        
        public DeleteDictionaryResponse(bool deleted) {
            this.deleted = deleted;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.word.hu/Word")]
    public partial class translationStub : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private long dictionaryIdField;
        
        private bool dictionaryIdFieldSpecified;
        
        private string originalField;
        
        private string translationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long dictionaryId {
            get {
                return this.dictionaryIdField;
            }
            set {
                this.dictionaryIdField = value;
                this.RaisePropertyChanged("dictionaryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dictionaryIdSpecified {
            get {
                return this.dictionaryIdFieldSpecified;
            }
            set {
                this.dictionaryIdFieldSpecified = value;
                this.RaisePropertyChanged("dictionaryIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string original {
            get {
                return this.originalField;
            }
            set {
                this.originalField = value;
                this.RaisePropertyChanged("original");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string translation {
            get {
                return this.translationField;
            }
            set {
                this.translationField = value;
                this.RaisePropertyChanged("translation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTranslationsForDictionary", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class GetTranslationsForDictionary {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long dictionaryId;
        
        public GetTranslationsForDictionary() {
        }
        
        public GetTranslationsForDictionary(long dictionaryId) {
            this.dictionaryId = dictionaryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTranslationsForDictionaryResponse", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class GetTranslationsForDictionaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Translation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public J2EE_SOAPtester.WordSoap.translationStub[] Translation;
        
        public GetTranslationsForDictionaryResponse() {
        }
        
        public GetTranslationsForDictionaryResponse(J2EE_SOAPtester.WordSoap.translationStub[] Translation) {
            this.Translation = Translation;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.word.hu/Word")]
    public partial class dictionaryStub : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDictionaries", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class GetDictionaries {
        
        public GetDictionaries() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDictionariesResponse", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class GetDictionariesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Dictionary", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public J2EE_SOAPtester.WordSoap.dictionaryStub[] Dictionary;
        
        public GetDictionariesResponse() {
        }
        
        public GetDictionariesResponse(J2EE_SOAPtester.WordSoap.dictionaryStub[] Dictionary) {
            this.Dictionary = Dictionary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewTranslation", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class NewTranslation {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long dictionaryid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string to;
        
        public NewTranslation() {
        }
        
        public NewTranslation(long dictionaryid, string from, string to) {
            this.dictionaryid = dictionaryid;
            this.from = from;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewTranslationResponse", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class NewTranslationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool created;
        
        public NewTranslationResponse() {
        }
        
        public NewTranslationResponse(bool created) {
            this.created = created;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewDictionary", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class NewDictionary {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type;
        
        public NewDictionary() {
        }
        
        public NewDictionary(string name, string type) {
            this.name = name;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewDictionaryResponse", WrapperNamespace="http://www.word.hu/Word", IsWrapped=true)]
    public partial class NewDictionaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.word.hu/Word", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool created;
        
        public NewDictionaryResponse() {
        }
        
        public NewDictionaryResponse(bool created) {
            this.created = created;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WordChannel : J2EE_SOAPtester.WordSoap.Word, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordClient : System.ServiceModel.ClientBase<J2EE_SOAPtester.WordSoap.Word>, J2EE_SOAPtester.WordSoap.Word {
        
        public WordClient() {
        }
        
        public WordClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J2EE_SOAPtester.WordSoap.EditTranslationResponse J2EE_SOAPtester.WordSoap.Word.EditTranslation(J2EE_SOAPtester.WordSoap.EditTranslation request) {
            return base.Channel.EditTranslation(request);
        }
        
        public bool EditTranslation(long id, string from, string to) {
            J2EE_SOAPtester.WordSoap.EditTranslation inValue = new J2EE_SOAPtester.WordSoap.EditTranslation();
            inValue.id = id;
            inValue.from = from;
            inValue.to = to;
            J2EE_SOAPtester.WordSoap.EditTranslationResponse retVal = ((J2EE_SOAPtester.WordSoap.Word)(this)).EditTranslation(inValue);
            return retVal.edited;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.EditTranslationResponse> J2EE_SOAPtester.WordSoap.Word.EditTranslationAsync(J2EE_SOAPtester.WordSoap.EditTranslation request) {
            return base.Channel.EditTranslationAsync(request);
        }
        
        public System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.EditTranslationResponse> EditTranslationAsync(long id, string from, string to) {
            J2EE_SOAPtester.WordSoap.EditTranslation inValue = new J2EE_SOAPtester.WordSoap.EditTranslation();
            inValue.id = id;
            inValue.from = from;
            inValue.to = to;
            return ((J2EE_SOAPtester.WordSoap.Word)(this)).EditTranslationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J2EE_SOAPtester.WordSoap.DeleteTranslationResponse J2EE_SOAPtester.WordSoap.Word.DeleteTranslation(J2EE_SOAPtester.WordSoap.DeleteTranslation request) {
            return base.Channel.DeleteTranslation(request);
        }
        
        public bool DeleteTranslation(long id) {
            J2EE_SOAPtester.WordSoap.DeleteTranslation inValue = new J2EE_SOAPtester.WordSoap.DeleteTranslation();
            inValue.id = id;
            J2EE_SOAPtester.WordSoap.DeleteTranslationResponse retVal = ((J2EE_SOAPtester.WordSoap.Word)(this)).DeleteTranslation(inValue);
            return retVal.deleted;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.DeleteTranslationResponse> J2EE_SOAPtester.WordSoap.Word.DeleteTranslationAsync(J2EE_SOAPtester.WordSoap.DeleteTranslation request) {
            return base.Channel.DeleteTranslationAsync(request);
        }
        
        public System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.DeleteTranslationResponse> DeleteTranslationAsync(long id) {
            J2EE_SOAPtester.WordSoap.DeleteTranslation inValue = new J2EE_SOAPtester.WordSoap.DeleteTranslation();
            inValue.id = id;
            return ((J2EE_SOAPtester.WordSoap.Word)(this)).DeleteTranslationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J2EE_SOAPtester.WordSoap.DeleteDictionaryResponse J2EE_SOAPtester.WordSoap.Word.DeleteDictionary(J2EE_SOAPtester.WordSoap.DeleteDictionary request) {
            return base.Channel.DeleteDictionary(request);
        }
        
        public bool DeleteDictionary(string id) {
            J2EE_SOAPtester.WordSoap.DeleteDictionary inValue = new J2EE_SOAPtester.WordSoap.DeleteDictionary();
            inValue.id = id;
            J2EE_SOAPtester.WordSoap.DeleteDictionaryResponse retVal = ((J2EE_SOAPtester.WordSoap.Word)(this)).DeleteDictionary(inValue);
            return retVal.deleted;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.DeleteDictionaryResponse> J2EE_SOAPtester.WordSoap.Word.DeleteDictionaryAsync(J2EE_SOAPtester.WordSoap.DeleteDictionary request) {
            return base.Channel.DeleteDictionaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.DeleteDictionaryResponse> DeleteDictionaryAsync(string id) {
            J2EE_SOAPtester.WordSoap.DeleteDictionary inValue = new J2EE_SOAPtester.WordSoap.DeleteDictionary();
            inValue.id = id;
            return ((J2EE_SOAPtester.WordSoap.Word)(this)).DeleteDictionaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J2EE_SOAPtester.WordSoap.GetTranslationsForDictionaryResponse J2EE_SOAPtester.WordSoap.Word.GetTranslationsForDictionary(J2EE_SOAPtester.WordSoap.GetTranslationsForDictionary request) {
            return base.Channel.GetTranslationsForDictionary(request);
        }
        
        public J2EE_SOAPtester.WordSoap.translationStub[] GetTranslationsForDictionary(long dictionaryId) {
            J2EE_SOAPtester.WordSoap.GetTranslationsForDictionary inValue = new J2EE_SOAPtester.WordSoap.GetTranslationsForDictionary();
            inValue.dictionaryId = dictionaryId;
            J2EE_SOAPtester.WordSoap.GetTranslationsForDictionaryResponse retVal = ((J2EE_SOAPtester.WordSoap.Word)(this)).GetTranslationsForDictionary(inValue);
            return retVal.Translation;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.GetTranslationsForDictionaryResponse> J2EE_SOAPtester.WordSoap.Word.GetTranslationsForDictionaryAsync(J2EE_SOAPtester.WordSoap.GetTranslationsForDictionary request) {
            return base.Channel.GetTranslationsForDictionaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.GetTranslationsForDictionaryResponse> GetTranslationsForDictionaryAsync(long dictionaryId) {
            J2EE_SOAPtester.WordSoap.GetTranslationsForDictionary inValue = new J2EE_SOAPtester.WordSoap.GetTranslationsForDictionary();
            inValue.dictionaryId = dictionaryId;
            return ((J2EE_SOAPtester.WordSoap.Word)(this)).GetTranslationsForDictionaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J2EE_SOAPtester.WordSoap.GetDictionariesResponse J2EE_SOAPtester.WordSoap.Word.GetDictionaries(J2EE_SOAPtester.WordSoap.GetDictionaries request) {
            return base.Channel.GetDictionaries(request);
        }
        
        public J2EE_SOAPtester.WordSoap.dictionaryStub[] GetDictionaries() {
            J2EE_SOAPtester.WordSoap.GetDictionaries inValue = new J2EE_SOAPtester.WordSoap.GetDictionaries();
            J2EE_SOAPtester.WordSoap.GetDictionariesResponse retVal = ((J2EE_SOAPtester.WordSoap.Word)(this)).GetDictionaries(inValue);
            return retVal.Dictionary;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.GetDictionariesResponse> J2EE_SOAPtester.WordSoap.Word.GetDictionariesAsync(J2EE_SOAPtester.WordSoap.GetDictionaries request) {
            return base.Channel.GetDictionariesAsync(request);
        }
        
        public System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.GetDictionariesResponse> GetDictionariesAsync() {
            J2EE_SOAPtester.WordSoap.GetDictionaries inValue = new J2EE_SOAPtester.WordSoap.GetDictionaries();
            return ((J2EE_SOAPtester.WordSoap.Word)(this)).GetDictionariesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J2EE_SOAPtester.WordSoap.NewTranslationResponse J2EE_SOAPtester.WordSoap.Word.NewTranslation(J2EE_SOAPtester.WordSoap.NewTranslation request) {
            return base.Channel.NewTranslation(request);
        }
        
        public bool NewTranslation(long dictionaryid, string from, string to) {
            J2EE_SOAPtester.WordSoap.NewTranslation inValue = new J2EE_SOAPtester.WordSoap.NewTranslation();
            inValue.dictionaryid = dictionaryid;
            inValue.from = from;
            inValue.to = to;
            J2EE_SOAPtester.WordSoap.NewTranslationResponse retVal = ((J2EE_SOAPtester.WordSoap.Word)(this)).NewTranslation(inValue);
            return retVal.created;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.NewTranslationResponse> J2EE_SOAPtester.WordSoap.Word.NewTranslationAsync(J2EE_SOAPtester.WordSoap.NewTranslation request) {
            return base.Channel.NewTranslationAsync(request);
        }
        
        public System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.NewTranslationResponse> NewTranslationAsync(long dictionaryid, string from, string to) {
            J2EE_SOAPtester.WordSoap.NewTranslation inValue = new J2EE_SOAPtester.WordSoap.NewTranslation();
            inValue.dictionaryid = dictionaryid;
            inValue.from = from;
            inValue.to = to;
            return ((J2EE_SOAPtester.WordSoap.Word)(this)).NewTranslationAsync(inValue);
        }
        
        public void ErrorTest() {
            base.Channel.ErrorTest();
        }
        
        public System.Threading.Tasks.Task ErrorTestAsync() {
            return base.Channel.ErrorTestAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J2EE_SOAPtester.WordSoap.NewDictionaryResponse J2EE_SOAPtester.WordSoap.Word.NewDictionary(J2EE_SOAPtester.WordSoap.NewDictionary request) {
            return base.Channel.NewDictionary(request);
        }
        
        public bool NewDictionary(string name, string type) {
            J2EE_SOAPtester.WordSoap.NewDictionary inValue = new J2EE_SOAPtester.WordSoap.NewDictionary();
            inValue.name = name;
            inValue.type = type;
            J2EE_SOAPtester.WordSoap.NewDictionaryResponse retVal = ((J2EE_SOAPtester.WordSoap.Word)(this)).NewDictionary(inValue);
            return retVal.created;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.NewDictionaryResponse> J2EE_SOAPtester.WordSoap.Word.NewDictionaryAsync(J2EE_SOAPtester.WordSoap.NewDictionary request) {
            return base.Channel.NewDictionaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<J2EE_SOAPtester.WordSoap.NewDictionaryResponse> NewDictionaryAsync(string name, string type) {
            J2EE_SOAPtester.WordSoap.NewDictionary inValue = new J2EE_SOAPtester.WordSoap.NewDictionary();
            inValue.name = name;
            inValue.type = type;
            return ((J2EE_SOAPtester.WordSoap.Word)(this)).NewDictionaryAsync(inValue);
        }
    }
}
